### ISSUE TITLE
Compatibility stu3 / dstu2 / R4 / etc

### ISSUE THREAD

**Issue by kaal-dam** [fhir-fli/fhir#9]
Is it possible to migrate for example a stu3.DocumentReference to a dstu2.DocumentReference easily ?

**Comment by Dokotela** [comment]
I'm afraid not, at least not with this library. The hl7 website does have some information about mapping between versions here,  http://hl7.org/fhir/STU3/r2maps.html, but I haven't put time into it. Some of the resources are substantially the same between versions, but others are not. Some of the resources themselves change names, but so do their fields, sometimes content from one resource is removed and used to create a separate resource in a different version, etc.
